### ISSUE TITLE
Not Maintained

### ISSUE THREAD

**Issue by ComfortablyCoding** [strapi-community/strapi-plugin-publisher#146]
Hello everyone, thanks for using the plugin!

I am unfortunately no longer maintaining this plugin due to some conflicts. If anyone wishes to take over as maintainer please contact @derrickmehaffy for the transfer.

**Comment by boazpoolman** [comment]
Hi!

Me and my team from [PluginPal](https://www.pluginpal.io) would like to take over maintenance for this plugin.
I've talked with @derrickmehaffy about it on Discord and he is OK with the transfer to our [Github organization](https://github.com/pluginpal).

I do need you (@ComfortablyCoding) to transfer the NPM package to my name, as you're currently the only one with access. My email address on my NPM account is boaz@uncinc.nl.

**Comment by derrickmehaffy** [comment]
I confirm the transfer of this to Boaz :)

**Comment by ComfortablyCoding** [comment]
Glad to hear! Invite sent! As maintenance has resumed I will close this issue.
